easy_admin:
    site_name: 'My Site Name'
    # site_name: '<img src="https://symfony.com/logos/symfony_white_01.png" />'

    user:
        # this method/property must return the string representation of the user
        # (Symfony will look for getFullName(), isFullName(), ..., and 'fullName' property)
        name_property_path: 'username'
        # avatar_property_path: 'avatar'

    design:
        # brand_color: '#1ABC9C'
        assets:
            # css: '//example.org/css/admin1.css'
            # js: '//example.org/js/admin1.js'
            favicon: '/assets/backend/favicon.png'

    entities:
        # List the entity class name you want to manage
        User:
            class: App\Entity\User
            list:
                fields: ['id', 'username', 'roles']
            new:
                fields:
                    - property: 'username'
                    - property: 'password'
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'User': 'ROLE_USER', 'Admin': 'ROLE_ADMIN' }}}
            edit:
                fields:
                    - property: 'username'
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'User': 'ROLE_USER', 'Admin': 'ROLE_ADMIN' }}}
